_target_: src.models.A2CStrategy
gamma: 0.9
max_grad_norm:
  actor: 0.1
  critic: 1.0
tau: 0.001
upload_onnx_sync: ${upload_onnx_sync}
epsilon_decay: 0.0004
epsilon_start: 1.0
epsilon_end: 0.01
episode_init_decay: 0
