actor:
  _target_: torch.optim.Adam
  lr: 0.01
  betas: [0.9, 0.999]
  eps: 1e-2
  weight_decay: 0
  amsgrad: False

critic:
  _target_: torch.optim.Adam
  lr: 0.01
  betas: [0.9, 0.999]
  eps: 1e-02
  weight_decay: 0
  amsgrad: False