_target_: torch.optim.lr_scheduler.ReduceLROnPlateau
mode: ${watch_metric.actor.watch_metric_mode}
factor: 0.1
patience: 1000
threshold: 0.0001
threshold_mode: rel
cooldown: 0
min_lr: 0
eps: 1e-08
verbose: True