defaults:
  - _self_
  - optimizer: adam
  - scheduler: ReduceLROnPlateau
  - trainer: default
  - model: ddpg
  - memory: default
  - dataloader: default
  - watch_metric: default
  - agent: ddpg
  - process_state: relative
  - env: FiraSimRewards

action_size: 2
sync_max_dist_update: 100
max_epochs: 10000000
batch_size: 4
project_name: reinforcement_learning
task_name: ddpg_refactored
is_debug: False
seed: 747
logdir: ./outputs