defaults:
  - _self_
  - optimizer: adam
  - scheduler: ReduceLROnPlateau
  - trainer: default
  - model: default
  - replaybuffer: default
  - strategy: a2c
  - dataset: default
  - dataloader: default
  - watch_metric: default
  - onnx: default
  - agent: default
  - test: default
  - process_state: absolute
  - env: FiraSim

action_size: 2
project_name: reinforcement_learning
task_name: ppo
is_debug: False
seed: 747
upload_onnx_sync: 10
pre_trained: False
logdir: ./outputs