defaults:
  - _self_
  - optimizer: adam
  - scheduler: ReduceLROnPlateau
  - trainer: default
  - model: default
  - replaybuffer: default
  - strategy: ppo
  - dataset: default
  - dataloader: default
  - watch_metric: default
  - agent: ppo
  - process_state: relative
  - env: ExponentialRewards

action_size: 2
project_name: reinforcement_learning
task_name: ppo
is_debug: False
seed: 747
logdir: ./outputs