defaults:
  - _self_
  - optimizer: adam
  - scheduler: ReduceLROnPlateau
  - trainer: default
  - model: ddpg
  - replaybuffer: default
  - strategy: ddpg
  - dataset: default
  - dataloader: default
  - watch_metric: default
  - agent: ddpg
  - process_state: relative
  - env: FiraSimRewards

action_size: 2
project_name: reinforcement_learning
task_name: ddpg
is_debug: False
seed: 747
logdir: ./outputs